/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.io.*;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Soumyadeep
 */
public class JFrame1 extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        this.setTitle("PhoneBook");
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfeid = new javax.swing.JTextField();
        tfnum = new javax.swing.JTextField();
        tfadd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfsearch = new javax.swing.JTextField();
        addbut = new javax.swing.JButton();
        delbut = new javax.swing.JButton();
        editbut = new javax.swing.JButton();
        exitbut = new javax.swing.JButton();
        clrbut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Phone Number:");

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHONEBOOK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Name: ");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Email ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Search");

        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfnameKeyPressed(evt);
            }
        });

        tfeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfeidKeyPressed(evt);
            }
        });

        tfnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfnumKeyPressed(evt);
            }
        });

        tfadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfaddKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone No.", "Address", "Email ID."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        tfsearch.setToolTipText("Type to search");
        tfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearchKeyReleased(evt);
            }
        });

        addbut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addbut.setText("Add");
        addbut.setToolTipText("Add a new contact");
        addbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbutActionPerformed(evt);
            }
        });

        delbut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delbut.setText("Delete");
        delbut.setToolTipText("Remove an existing contact");
        delbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbutActionPerformed(evt);
            }
        });

        editbut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editbut.setText("Update");
        editbut.setToolTipText("Update an existing contact");
        editbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbutActionPerformed(evt);
            }
        });

        exitbut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitbut.setText("Exit");
        exitbut.setToolTipText("Exit the app");
        exitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutActionPerformed(evt);
            }
        });

        clrbut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clrbut.setText("Clear");
        clrbut.setToolTipText("Clear the text fields");
        clrbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfadd, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfeid, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(addbut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delbut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editbut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clrbut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitbut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(tfnum))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfadd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfeid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delbut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editbut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitbut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clrbut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbutActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        var n = tfname.getText();
        if(n.equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the name of the contact."); 
        }
        else
            model.addRow(new Object[]{tfname.getText(),tfnum.getText(), tfadd.getText(), tfeid.getText()});
        
        save();
    }//GEN-LAST:event_addbutActionPerformed

    private void delbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbutActionPerformed

       // TODO add your handling code here:
       
       if(jTable1.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null,"No contact selected.");  
        }
       else{
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do you want to remove this contact?","Remove Contact", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int rowindex=jTable1.getSelectedRow();
        model.removeRow(rowindex);
        }
        
        save();
       }
    }//GEN-LAST:event_delbutActionPerformed

    private void editbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbutActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        var n = tfname.getText();
        if(n.equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the name of the contact."); 
        }
        else{
        int i = jTable1.getSelectedRow();     
                if(i >= 0) 
                {
                   model.setValueAt(tfname.getText(), i, 0);
                   model.setValueAt(tfnum.getText(), i, 1);
                   model.setValueAt(tfadd.getText(), i, 2);
                   model.setValueAt(tfeid.getText(), i, 3);
                }
                
                save();
        }
    }//GEN-LAST:event_editbutActionPerformed

    private void tfsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearchKeyReleased
        // TODO add your handling code here:
        filter(1);
    }//GEN-LAST:event_tfsearchKeyReleased
    
    private void filter(int n)
    {
        
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        String s=tfsearch.getText();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<>(model);
        if(n==1){
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" +s));
        }
        else if(n==0)
        {
            System.out.println("Does this thing even work?");
            tr.setRowFilter(null);
        }
    }
    
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
            tfname.setText("");
            tfnum.setText("");
            tfadd.setText("");
            tfeid.setText("");
            int s=tfsearch.getText().length();
            
            if(s==0){
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int j=jTable1.getSelectedRow();
            System.out.println(j);
            if(jTable1.getValueAt(j,0) == null)                   
                        tfname.setText("");              
            else
                tfname.setText(String.valueOf(model.getValueAt(j,0)));
            
            if(jTable1.getValueAt(j,1) == null)
                tfnum.setText("");
            else
                tfnum.setText(String.valueOf(model.getValueAt(j,1)));
            
            if(jTable1.getValueAt(j,2) == null)
                tfadd.setText("");
            else
                tfadd.setText(String.valueOf(model.getValueAt(j,2)));
            
            if(jTable1.getValueAt(j,3) == null)
                tfeid.setText("");
            else
                tfeid.setText(String.valueOf(model.getValueAt(j,3))); 
            }
            else
            {
                filter(0);
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int j=jTable1.getSelectedRow();
            System.out.println(j);
            if(jTable1.getValueAt(j,0) == null)                   
                        tfname.setText("");              
            else
                tfname.setText(String.valueOf(model.getValueAt(j,0)));
            
            if(jTable1.getValueAt(j,1) == null)
                tfnum.setText("");
            else
                tfnum.setText(String.valueOf(model.getValueAt(j,1)));
            
            if(jTable1.getValueAt(j,2) == null)
                tfadd.setText("");
            else
                tfadd.setText(String.valueOf(model.getValueAt(j,2)));
            
            if(jTable1.getValueAt(j,3) == null)
                tfeid.setText("");
            else
                tfeid.setText(String.valueOf(model.getValueAt(j,3))); 
                
            }
          
        
    }//GEN-LAST:event_jTable1MousePressed

    private void exitbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do you want to exit the application?","Exit", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_exitbutActionPerformed

    private void clrbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbutActionPerformed
        // TODO add your handling code here:
            tfname.setText("");
            tfnum.setText("");
            tfadd.setText("");
            tfeid.setText("");
    }//GEN-LAST:event_clrbutActionPerformed

    private void tfnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnumKeyPressed
        // TODO add your handling code here:
         if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')|| evt.getKeyChar()=='\b'|| evt.getKeyChar()=='*' || evt.getKeyChar()=='#' || evt.getKeyChar()=='+' || evt.getKeyChar()==' '|| evt.getKeyChar()=='-' || evt.getKeyChar()=='.') {
               tfnum.setEditable(true);
            } else {
               tfnum.setEditable(false);
            }
    }//GEN-LAST:event_tfnumKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        File file = new File("Contacts.txt");
        try {
            
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split("¶");
                model.addRow(row);
            }
        } 
        catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void tfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '¶')
            tfname.setEditable(false);              
    }//GEN-LAST:event_tfnameKeyPressed

    private void tfaddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfaddKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '¶')
            tfnum.setEditable(false);               
    }//GEN-LAST:event_tfaddKeyPressed

    private void tfeidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfeidKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '¶')
            tfeid.setEditable(false);
                
    }//GEN-LAST:event_tfeidKeyPressed

    void save()
    {
        File file = new File("Contacts.txt");
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            for(int i = 0; i < jTable1.getRowCount(); i++){//rows
                for(int j = 0; j < jTable1.getColumnCount(); j++){//columns
                    if(jTable1.getValueAt(i, j) == null)
                    {
                        bw.write(""+"¶");
                    }
                    else{
                    bw.write(String.valueOf(jTable1.getValueAt(i,j)));
                    bw.write("¶");
                    
                    }
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            tfname.setText("");
            tfnum.setText("");
            tfadd.setText("");
            tfeid.setText("");
        } catch (IOException ex) {
            System.out.println("exception");
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbut;
    private javax.swing.JButton clrbut;
    private javax.swing.JButton delbut;
    private javax.swing.JButton editbut;
    private javax.swing.JButton exitbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfeid;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfnum;
    private javax.swing.JTextField tfsearch;
    // End of variables declaration//GEN-END:variables
}
